name: Tennis Court Availability Monitor

# 24/7 monitoring for St Johns Park tennis courts

on:
  schedule:
    # Run every 30 minutes from 6 AM to 11 PM UK time (5 AM to 10 PM UTC)
    - cron: '*/30 5-22 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-courts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check court availability
      run: python github_runner.py
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: court-check-logs-${{ github.run_number }}
        path: court_check.log
        retention-days: 7